development:
  session_key: h8ter_development
  session_secret: XSheUg1YEEkLX6bSCJYiwgNiV859hL2q
  site_url: http://example.com

test:
  session_key: h8ter_test
  session_secret: 1mF89VtBzDu5doFDnu3pfJHLRJxwaFzH
  site_url: http://example.com
  
production:
  session_key: h8ter_development
  session_secret: XSheUg1YEEkLX6bSCJYiwgNiV859hL2q
  site_url:  http://gentle-flower-366.heroku.com/
  